### ISSUE TITLE
next release?

### ISSUE THREAD

**Issue by patroqueeet** [Develatio/django-walletpass#30]
@alexandernst do we want to publish it?

**Comment by alexandernst** [comment]
I think yes, there are enough (breaking) changes. I'd say this should be 4.0

**Comment by patroqueeet** [comment]
🆗  -> 🚀  

:)

**Comment by GonzaloMachado** [comment]
Hello!

First, thank you for your hard work and dedication in developing and maintaining the library. It has been very useful tool for my projects.

I noticed that the version available on PyPI is 3.0 and that there have been significant updates and improvements in the GitHub repository since that release. 

Could you please let me know if there are any plans to publish the latest version of the library to PyPI?

Looking forward to your response.

**Comment by alexandernst** [comment]
We should have released this half an year ago. Let me do it today :)

**Comment by alexandernst** [comment]
4.0 has been officially released! :) 

https://pypi.org/project/django-walletpass/4.0/

**Comment by GonzaloMachado** [comment]
Hi @alexandernst .

Thank you so much for publishing the latest version on PyPi! I appreciate your prompt response.

While i was fully testing the new version, I encountered something that I’d like to discuss further.
I’ll be opening a new issue with the details.

Thanks again for your great work!
